all: dequeaslistdriver

dequeaslistdriver: dequeaslistdriver.cpp projectdriver.h projectdriver.cpp
	g++ -std=c++11 -o dequeaslistdriver dequeaslistdriver.cpp projectdriver.cpp

clean:
	rm dequeaslistdriver